default: "3.12.13"
type: runtime
source: python-build-standalone
homepage: "https://github.com/astral-sh/python-build-standalone"
channels:
  stable: "3.12.13"
  "3.12": "~3.12.0"
  "3.13": "~3.13.0"
  "3.14": "~3.14.0"
